### DISCUSSION TITLE
How can I use ShopCTL in GitHub CI?

### DISCUSSION THREAD

**Discussion by ankitpokhrel** [ankitpokhrel/shopctl#6] [FAQs]
This guide explains how to configure ShopCTL in the GitHub CI pipeline.

> [!TIP]
> Check [this article](https://medium.com/@ankitpokhrel/how-we-built-an-ai-powered-automated-product-enrichment-pipeline-for-shopify-4acfe44fee0e) for additional details.

### 1. ShopCTL config

Before we set up the CI pipeline, we need to manually (for now) create a ShopCTL config file. This config defines your Shopify store context and is required for all ShopCTL commands to work properly. 

The config is fairly simple and looks like the one below. Replace all occurances `store1` with your myshopify subdomain alias and save it under `shopctl/.shopconfig.yml` inside your project root directory.

```yml
# shopctl/.shopconfig.yml

ver: v0
contexts:
    - alias: store1 # Replace me
      store: store1.myshopify.com # Replace me
currentContext: store1 # Replace me
```

### 2. Create a custom GitHub action

To avoid repeating installation steps across multiple workflows, define a reusable action for setting up ShopCTL. This custom action will install Go and the ShopCTL CLI.

> Place reusable actions under `.github/workflows/actions/` or `.github/actions/` depending on your repo’s structure. Refer to them in workflows with a relative path (e.g., `./.github/workflows/actions/setup-shopctl`).

```yml
# .github/workflows/actions/setup-shopctl/action.yml

name: Setup ShopCTL
description: Installs Go and ShopCTL CLI
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.24"

    - name: Install ShopCTL
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libx11-dev
        go install github.com/ankitpokhrel/shopctl/cmd/shopctl@main
        echo "$HOME/go/bin" >> "$GITHUB_PATH"
```

### 3. Reference it to your pipeline

You can now reference your custom `setup-shopctl` action in any workflow. Here's an example pipeline that runs a product validation script daily:

```yml
# .github/workflows/validate-products.yml

name: Product Validation Pipeline

on:
  schedule:
    - cron: "0 1 * * *"  # Every day at 1 AM UTC
  workflow_dispatch:

jobs:
  validate-products:
    runs-on: ubuntu-latest
    env:
      SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }} # We need access token
      SHOPIFY_CONFIG_HOME: ${{ github.workspace }} # Instruct shopctl to look for config in project dir
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup ShopCTL
        uses: ./.github/workflows/actions/setup-shopctl # This is the shopctl action we created

      - name: Run validation script
        run: |
          chmod +x scripts/validate_recent_products.sh
          ./scripts/validate_recent_products.sh | tee validation.log

      - name: Upload log
        uses: actions/upload-artifact@v4
        with:
          name: validation-log
          path: |
            validation.log
            invalid_products.csv # This artifact is generated by the `validate_recent_products.sh` script
```
